In [13]:
import numpy as np
import pandas as pd
import pyarrow
import openai
import bertopic
from bertopic.vectorizers import ClassTfidfTransformer
from bertopic.representation import KeyBERTInspired, MaximalMarginalRelevance
from sklearn.feature_extraction.text import CountVectorizer
from bertopic.representation import OpenAI
from sentence_transformers import SentenceTransformer
pd.set_option('display.max_colwidth', None)

### Load the Data

In [14]:
masked_char_df = pd.read_parquet("/data/characterai/updated/mask_result.parquet")

In [15]:
embeddings = np.load("/data/characterai/updated/allmpv2_embeddings.npy")

In [16]:
masked_char_df.shape

(2365436, 3)

In [17]:
masked_char_df['str_len'] = masked_char_df.greeting.str.len()
matching_inds = np.where((masked_char_df.str_len >= 500))[0]

masked_char_df.loc[matching_inds].shape[0]/len(masked_char_df)

0.14948787453983114

In [19]:
masked_char_df['str_len'] = masked_char_df.greeting.str.len()
matching_inds = np.where((masked_char_df.str_len >= 50) & (masked_char_df.str_len <500))[0]
masked_char_df = masked_char_df.loc[matching_inds]
docs = masked_char_df.greeting.to_list()
embeddings= embeddings[matching_inds, :]

len(docs), len(embeddings)

(1782006, 1782006)

### Train the Model

In [7]:
vectorizer_model = CountVectorizer(min_df=5, stop_words="english")


sentence_model = SentenceTransformer("sentence-transformers/all-mpnet-base-v2", 
                                     trust_remote_code=True,
                                    cache_folder= "./st_cache")

ctfidf_model = ClassTfidfTransformer(reduce_frequent_words=True)

client = openai.OpenAI(api_key="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")
oai_model = OpenAI(client, prompt="""
I have a topic that contains the following character.ai greetings:
[DOCUMENTS]

This set of greetings is described by the following keywords: [KEYWORDS]

Based on the information above, extract a topic label in the following format for this set of character.ai greetings:
topic: <topic label>
""",
                  model="gpt-4o-mini", nr_docs=10, diversity=.2)

representation_model = {
    #"KeyBERTInspired": KeyBERTInspired(),
    "MaximalMarginalRelevance": MaximalMarginalRelevance(),
    "GPT": oai_model
}

from umap import UMAP
model = bertopic.BERTopic(
    verbose=True,
    low_memory=False,
    min_topic_size=250,
    embedding_model=sentence_model,
    vectorizer_model=vectorizer_model,
    ctfidf_model=ctfidf_model,
    umap_model= UMAP(n_neighbors=15, n_components=8, metric='cosine', low_memory=False),
    representation_model=representation_model,
)

In [ ]:
model = model.fit(docs, embeddings=embeddings)

2025-05-08 21:52:05,142 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm

In [ ]:
model.save("/data/characterai/updated/bert_allmpni_kj_5_8_25_diversity_250_min", serialization="safetensors", save_ctfidf=True)

# Analyze Results

In [7]:
import bertopic
model =  bertopic.BERTopic.load("/data/characterai/updated/bert_allmpni_kj_5_8_25/")

2025-08-29 15:00:11,527 - BERTopic - WARNING: You are loading a BERTopic model without explicitly defining an embedding model. If you want to also load in an embedding model, make sure to use `BERTopic.load(my_model, embedding_model=my_embedding_model)`.

In [8]:
inf = model.get_topic_info()
inf[inf.Topic == 60]

,Topic,Count,Name,Representation,MaximalMarginalRelevance,GPT,Representative_Docs
61,60,2822,60_barista_coffee_cafe_café,"[barista, coffee, cafe, café, waiter, order, s...","[barista, cafe, café, waiter, starbucks, custo...",[Café Interactions and Barista Experiences],NaN

In [20]:
# Extract the top 50 representative documents

# Prepare your documents to be used in a dataframe
documents = pd.DataFrame({"Document": docs,
                          "ID": range(len(docs)),
                          "Topic": model.topics_})
repr_docs, _, _, _= model._extract_representative_docs(c_tf_idf=model.c_tf_idf_,
                                                          documents=documents,
                                                          topics=model.topic_representations_ ,
                                                          nr_repr_docs=1)

In [21]:

topic_rep = model.get_topic_info()
topic_rep['repr_docs'] = ["\n\n\n".join(repr_docs[top]) for top in topic_rep.Topic]
topic_rep.to_latex("topic_info_table.csv",index=False)

In [22]:
len(topic_rep[topic_rep.Count > 1000])

131

In [23]:
topic_rep['repr_docs_min'] = topic_rep.repr_docs.str[:250]
topic_rep['name'] = topic_rep.GPT.apply(lambda x: x[0])

In [24]:
print(topic_rep[topic_rep.Count > 1000][['name','Count',"repr_docs_min"]].to_latex(index=False))

\begin{tabular}{lrl}
\toprule
name & Count & repr_docs_min \\
\midrule
Intriguing Encounters in Various Settings & 967852 & "Hm. I wasn't expecting a new recruit."
[MASK] said in a somewhat calm tone, he glanced at you. You worked for the Japanese Police, nothing about you was suspicious.
[MASK]'s face lit up, he looked at you and waved. You waved back.
"That's [MASK], I  \\
Lazy Characters in Casual Interactions & 52409 & "HeeEellooOOoo ttthhheeerrreee, strange ghost/mortal!! Welcome to the Underworld Office! We don't hurt people here..usually."
She said with a playful and confident tone in her voice. She placed both hands on her hips as she looks at you closely. Her  \\
Concert Experiences and Celebrity Interactions & 40865 & ~ Tokio hotel live concert ~
Tokio hotel were gone on tour [MASK] is the lead guitarist and he’s also [MASK]’s boyfriend.
They we’re performing in front of millions of people while [MASK] went to [MASK] he saw him crying silently and [MASK] new exact \\
Arranged Marriage Dynamics & 36583 & After your parents passed away, your grandmother arranged you a marriage with some man, the son of some rich family. Your father had a successful business so she wanted your husband to take over it and be a CEO.
You hated this marriage. You absolutel \\
Relationship Turmoil and Emotional Conflict & 36172 & You and your bf [MASK] were laying in bed, cuddling. it was already morning when you tried to get up, but [MASK] pulled you back to the bed. You told him that you needed to go get ready for the day. And you looked at him again and he was crying. You  \\
Emotional Support and Comforting Conversations & 28008 & Hello. You can vent to me whenever you feel the need to. You can tell me about all of your problems. I won’t judge you. I will always love you and will make sure you’re okay. I care about your mental health. I will always look out for you. I will alw \\
Highschool Friendship and Secret Crushes & 27897 & You and [MASK] had been friends ever since Highschool. You two were inseparable. Now, you guys were in your last year of Highschool. And, despite being the closest of friends, [MASK] had developed feelings for you overtime. He kept quiet about it, of \\
Sibling Dynamics and Family Relationships & 26666 & [MASK], your older brothers best friend is your enemy. He is 19 and you are 17. You've hated each other since you two met although he is quite flirty. His family likes you and your family likes him. Since he is your older brothers best friend both of \\
Royal Court Dynamics and Marriage Alliances & 22121 & You are a princess/prince and now you are 20 years old now, and your parents decided to look for a prince from another kingdom, to marry you. You were standing next to your father who was sitting on the king's chair.
Not long after, the prince came,  \\
Mafia Romance and Rivalries & 16034 & [MASK] is your boyfriend who works in Port Mafia as one of the five executives. While you work in their rival company, Armed Detective Agency, you are a former mafia in Port mafia, but You quit and move to Armed Detective Agency since it's safer, [MA \\
Magical Cats and Adoptions & 13121 & In the middle of the night, you woke up by the sound of a knocking door. You get up from the bed and went to the door to answer it. After you opened it, there's a black cat with a beautiful shiny green eyes.
Meow..~
He meowing softly as he looks like \\
Character Greetings and Introductions & 11050 & [MASK] gives a warm smile and extends her hand for a firm handshake. "Hi there, I'm [MASK]. It's a pleasure to meet you!" \\
Pregnancy and Family Dynamics & 10225 & after catching your husband having an affair with his secretary you left and divorced him but a couple months later you took a pregnancy test finding out you were pregnant
3 years later
your son is now 3 years old and as you were making him a snack w \\
College Roommate Introductions & 10040 & It’s your first day of college, and you’re looking for your dorm room.
You eventually find it and meet your roommate, he looks up at you and waves.
Oh hello there, you must be my new roommate. \\
Task Force 141 Dynamics and Challenges & 9585 & Task force 141, had recruited 2 pick me’s. and the operators of task force 141, like captain [MASK], lieutenant [MASK], sergeant mactavish or known as soap, gaz, and you. We’re in the room. Waiting for the 2 recruits.
[MASK]: “they’ll arrive about… n \\
FNAF Animatronics and Pizzeria Experiences & 8550 & Uh, hello? Hello, hello? Uh, hello and welcome to your new summer job at the new and improved Freddy Fazbear's Pizza! On the Security office you'll find 2 vents, with its own separate lights and a hallway, which can be light up using torch. Be carefu \\
Workplace dynamics between a strict CEO and their personal secretary & 7780 & You started working as an assistant for the CEO of a wealthy business company a few months ago. Your boss, [MASK], wasn’t so kind at first. However, overtime he has grown a bit fond of you. He even treats you just a bit nicer than all of the other em \\
Rainy Encounters and Umbrella Moments & 7599 & [MASK] is running through the wet and rainy street, your running because you don't have a umbrella, you need to find a place that you will stop to.
While your running you bumped into someone and fell on the ground, you looked up and saw a tall guy we \\
Vampire Hunters and the Secret Life of Vampires & 7445 & (Her name is [MASK], she's the daughter of a famous vampire hunter and is following his legacy. She is a calm girl but only when not hunting, few were the vampires who survived a fight against her. She just moved to your town, and you, a vampire, is  \\
Task Force 141 Introductions and Ghostly Encounters & 7421 & (You were part of the ghosts and were on break so [MASK] decided to meet up with task force 141.)
[MASK]: Who’s the big guy (ghost)?
[MASK]: [MASK]’s jealous!
[MASK]: shut it, [MASK].
[MASK]: the names ghost.
[MASK]: see this isn’t so bad!
Soap: hey  \\
Unrequited Crush and Friendship Dynamics & 7279 & on your way home you see a childhood friend you used to have a crush on you moved away and never confessed to her she sees you and runs up too you
Wait [MASK] is that you wow you’ve grown up so much [MASK] how’ve your been, your still so cute, wait d \\
Bar Encounters and Drinking Experiences & 7252 & To take your mind off the chaos, you went to the bar for a drink. You wouldn't even think that you would see [MASK], the popular boy of the basketball club, there.
You sat on the chair and looked at the liquor shelves. Until you heard [MASK]'s voice
 \\
Medical Interactions in Psychiatric Settings & 7039 & Today is your first day working in a psychiatric hospital as a personal nurse for one of the patients here. And that patient is [MASK], A crazy psychopath who has killed many people.
All the previous nurses had been killed by [MASK] because he didn't \\
Demon Slayer Adventures & 6992 & [MASK]: We Must move quickly the demon slayer corps leader summoned us 2 some demon slayers sent to stop demons in a village area need our [MASK] assistance i always forget how forgetful you are \\
Baking Adventures & 6583 & [MASK]'s birthday was coming up soon, and [MASK] wanted to try to make a cake for them. He had all the ingredients and the recipe. Everything was perfect!
That was until [MASK] added too much flour, didn't mix the eggs in properly, and used the wrong \\
Boxing and Training Dynamics & 6195 & 🥊[MASK] [MASK]
You have just joined a boxing gym called Kamogawa Boxing Gym
You meet some fellow boxers as well.
[MASK]: Welcome, I’m [MASK]!
[MASK]: Hm? Don’t get in my way kid.
[MASK]: Ah! More competition?
[MASK]: Go easy on him! He just joined
[M \\
Bot Request and Social Links & 6154 & DISCORD SERVER
-----✧✦--------
https://discord.com/invite/enNQQf65
↓
DISCORD ACCOUNT
--------✦✧-----
lvvdove
:
:
REQUEST FORM LINK; GOOGLE FORM
↓
https://docs.google.com/forms/d/e/1FAIpQLSf6sAXHhx-mOpJ5ug-gGKVlkaxknS-ZHyqOY1Jbzi0QiGpIEg/viewform?usp= \\
School Bullying Dynamics & 6056 & [MASK] is with golden eyes and white hair.
In high school, he was a so-called 'bully'. But its purpose is only to prevent innocent people at school from being bullied. he was bullying other bullies, and because of that the kids at school moved furthe \\
Smoking and Relationships & 5956 & You and [MASK] are in a relationship.
[MASK] doesn’t allow you to smoke, though he smokes himself. He says it’s bad for your health.
One night, you stole a cigarette from his pocket without him noticing since he was asleep. You opened the balcony doo \\
Heaven and Hell Dynamics & 5952 & you are the angel [MASK], there are less than 10 such angels left, you are a kind and fragile girl
while walking through the Garden of Eden, you saw black wings, you knew that demons live in hell, but someone snuck into heaven, you saw him, [MASK]. t \\
Countryhumans Sleepover Chaos & 5782 & Germany: hey guys why does this guy create so many character
USA: I don’t know
Russia: slurping vodka I am drunk and I’m going to drink more
China: I am the real China!
Taiwan: NO IM THE REAL CHINA
Japan: watching anime
Germany: drinking beer
South K \\
Sports Interactions and Relationships & 5639 & [MASK] is the new Assistant Coach of the Karasuno Volleyball team, today is your first day! You stand inside the gymnasium beside [MASK], a 3rd year who is captain of the Karasuno volleyball team. You introduce yourself to the players as well as meet \\
Relationship Dynamics and Affection & 5422 & [MASK] is your girlfriend,she’s a really beautiful woman,she’s caring and protective,sometimes she can be jealous,she’s really kind to you but rude to others,she always takes care of you and helping you with everything and she loves your princess tre \\
Laboratory Experiments and Test Subjects & 5076 & You're a kidnapped test subject that's being experimented on by mad scientist. Apparently they called you: Test subject 01
And the experiment is called: Creating a human bioweapon.
You are inside a capsule surrounded by a weird liquid substance. You  \\
Supernatural Encounters in Shadowy Environments & 4861 & You're sitting on your couch and watching TV. Suddenly, you hear a loud banging and screeching noise coming from outside. You stand up and look out the window, and you see a tall, creepy figure standing in your backyard. It continues to stare at you  \\
Spider-Verse Adventures & 4774 & you just got into the spider society and you meet [MASK]! he wants to show you around
"hi!" \\
Friendship and Connection & 4694 & -*𝐘𝐨𝐮 𝐚𝐧𝐝 𝐦𝐢𝐠𝐮𝐞𝐥 𝐡𝐚𝐬 𝐛𝐞𝐞𝐧 𝐟𝐫𝐢𝐞𝐧𝐝𝐬 𝐬𝐢𝐧𝐜𝐞 𝐤𝐢𝐧𝐝𝐞𝐫𝐠𝐚𝐫𝐭𝐞𝐧 𝐚𝐧𝐝 𝐧𝐨𝐰 𝐲𝐨𝐮 𝐠𝐮𝐲𝐬 𝐚𝐫𝐞 in high school 𝐲𝐨𝐮 𝐰𝐞𝐫𝐞 𝐨𝐧 𝐟𝐚𝐜𝐞𝐭𝐢𝐦𝐞 𝐰𝐢𝐭𝐡 𝐦𝐢𝐠𝐮𝐞𝐥 𝐚𝐧𝐝 𝐢𝐭 𝐰𝐚𝐬 𝐅𝐫𝐢𝐝𝐚𝐲 𝐡𝐞 𝐰𝐚𝐬 𝐩𝐥𝐚𝐲𝐢𝐧 𝐭𝐡𝐞 𝐠𝐚𝐦𝐞 𝐰𝐢𝐭𝐡 𝐡𝐢𝐬 𝐟𝐫𝐢𝐞𝐧𝐝 𝐚𝐧𝐝 𝐨𝐧𝐞 𝐨𝐟 𝐡𝐢𝐬 𝐟𝐫𝐢𝐞𝐧𝐝𝐬 𝐬𝐚𝐲 “𝐲𝐨𝐮𝐫 𝐨𝐧 𝐭𝐡𝐞 𝐩𝐡𝐨𝐧𝐞 𝐰𝐢𝐭𝐡 𝐭𝐡𝐚𝐭 𝐠𝐢𝐫𝐥 𝐡𝐮𝐡?“ 𝐡𝐢𝐬  \\
Hogwarts Student Life and Friendships & 4644 & (You are a student at Hogwarts, the magical school, the fellow students in your year are:)
[MASK]: A Gryffindor who plays seeker in the Gryffindor quidditch team.
[MASK]: A Ravenclaw.
[MASK]: A Ravenclaw.
[MASK]: A Gryffindor who plays keeper in the  \\
Dragon Encounters and Transformations & 4496 & You were a mysterious dragon rider that the Dragon Riders had spotted and chased after. You and your dragon companion have been exploring together but this was a "minor" interuption.
[MASK]: “They’re not getting away, come on bud.“
[MASK] spoke to hi \\
Mermaid and Siren Encounters & 4461 & You were and mermaid/siren and he caught you in a net he was just fishing for fish “LET ME GO!” You said and [MASK] “we just got lucky!” \\
Detective vs. Criminal Investigation & 4445 & (read desc) [MASK] is a police officer and detective, in charge of high level crime cases. you, a criminal, are who hes investigating. no one has been able to catch you before.. he was the closest person, but, after finding out your identity he feels \\
Werewolf Encounters and Pack Dynamics & 4396 & [MASK] is a werewolf , is full moon now , and you notice he slowly be come a wolf , you look [MASK]
[MASK] "run away from me now!!" yell , he become a werewolf \\
Family Dynamics and Emotional Struggles & 4313 & you are a kid who is 7 years old [MASK] is your father and has been a single father with you since you were born because your mother left you both and never returned. [MASK] takes good care of you and makes sure you are safe and loved
it is morning a \\
Zombie Apocalypse Survival & 4169 & *You were walking down an abandoned, empty road. You lost your group to the zombies. Only you survived. [MASK], [MASK], and [MASK] are your BEST FRIENDS from U.A before the zombie apocalypse started. You four have been separated. [MASK], [MASK], and  \\
Villains vs. Heroes in a Superhero Universe & 4149 & You're a student of UA, and the LOV attacked the school. There were so many villains that all the pro heroes were stuck fighting the strongest villains
You stand there looking around at your classmates. All of them are very badly hurt. You know that  \\
Bodyguard Protection for Spoiled Youth & 4144 & I’m the bodyguard your dad has hired to keep you in your room. I’ll be on watch right outside of your room. \\
Family Dynamics and Relationships & 4031 & I am [MASK] I have a boyfriend named [MASK] and we kiss all the time I have a dorky sister named [MASK] and a brother named [MASK] i'm the oldest I have a step grandma who's younger than my mom and she has a kid her name is [MASK] and her kids name i \\
Roommate Streamer Dynamics & 3822 & you are a famous Twitch streamer and your roommate [MASK] was one as well, both of you guys knew each other for a long time and had been roommates for almost two months already,this is why most of his viewers would ship you two,just because of how go \\
Amazing Digital Circus VR Experience & 3787 & You have put on a Headset and been sent to The Amazing Digital Circus the First thing you see is a Jester ([MASK]) she's still getting used to the Amazing digital circus \\
Demon Slayer Hashira Introduction and Interactions & 3601 & you are a new hashira (aka the 10th hashira),you were with master [MASK] and the hashiras in a room, (p.s you need to know the basic information of demon slayer or it will be confusing)(also you can pick your gender)
“[MASK] is the new hashira, why d \\
Music Artists and Their Roles & 3507 & I’m [MASK], songwriter and a producer. A lot of people know me as the bassist and co-lead vocalist from Blink-182, though. \\
Dance Rivalry and Artistic Collaboration & 3502 & It was late and everybody left the studio and you were alone, as you thought you were.
Purple LED lights in the dancing studio, dancing to tiktok trend you saw and dance to it for fun
As you continue dancing in front of the mirror, here comes the par \\
Ice Skating and Hockey Interactions & 3452 & you are an figure skater, you were skating on the rink before the hockey boys came to practise. You always were therr before their training to see your brothers [MASK]. As you were skating the hockey boys came onto the ice and [MASK] skated towards y \\
Drone Encounters on Copper-9 & 3431 & You were a murder drone in the year of 3071. You had friends, [MASK], J and V, but your BEST friend was N. Serial Designation N. He was a murder drone that didnt like killing worker drones. He was rather nice. The group decided to meet in the pod at  \\
Dog Encounters and Adventures & 3371 & [MASK], but he's a dog and you're [MASK].
One fine day, an ordinary boy named [MASK] was turned into a dog. He still thinks like a human, but only one person can hear him, and that's [MASK], who is unfortunately afraid of dogs.
Having turned into a d \\
Birthday Celebrations & 3181 & just a bot to wish u a very happy birthday use this on ur birthday
HAPPY BIRTHDAY
gives you some gifts and a cake
WOAH HAPPY BIRTHDAY [MASK] \\
RPG Character Creation and Roleplay Prompts & 3117 & What you wanna put for character definition if it’s a person:
Character("")
Age("")
Gender("")
Race("")
Sexuality("")
Appearance("")
Height("")
Species("")
Body("")
Likes("")
Dislikes("")
Personality("")
Skills("")
Occupation("")
Backstory("")
Rolepl \\
New Neighbor Greetings and Interactions & 2973 & you have just moved to a very colorful neighborhood called "welcome home" you were taking down the moving boxes until someone comes up and smiles at you
"hello dear neighbor, I see that you are new, well, my name is [MASK] and what is your name?"
spe \\
F1 Racing Adventures & 2942 & You’re a 19 year old girl working as an engineer for Ferrari. Your mind is heavily focused on fixing a F1 car.
The drivers had finished racing the Singapore Grand Prix. As [MASK] was exiting his F1 car. You caught his eye, from the Ferrari garage. He \\
Christmas Celebrations and Traditions & 2929 & It is the day before Christmas Eve and it has been snowing outside all day and your house smells wonderful of baked cookies and you are very impatient about Christmas Eve and then after the long snowy day, the time has finally come: It is finally Chr \\
Character Greetings Introductions & 2881 & Hi my names [MASK]!!! It’s so so nice to meet you :D what’s your name? \\
Café Interactions and Barista Experiences & 2822 & As usual, you went to the coffee shop before work. You were a regular customer at this coffee shop. Your favorite barista was a guy named [MASK]. You came here because they sell good coffee... or because of barista [MASK].
"Today, too, latte?" asked  \\
Sleep and Wakefulness & 2725 & it was a dark night outside, and [MASK] was fast asleep in his bed, but suddenly someone knocked on the door. Who could it be so late?
[MASK] wakes up from loud knocking, slowly and sleepily he walked to the door and opened it. [MASK] stood behind he \\
Artistic Encounters and Inspirations & 2685 & As you sit in art class, you being the muse for the artists the surround you, you notice a painter who’s eyes are practically glued only to you, not the canvas, but you.
As the class comes to a finish you get up and curiosity gets the best of you, yo \\
Tutor and Student Relationship in Academic Improvement & 2540 & POV: [MASK] as your tutor
You're not smart and you always have low grades , your parents didn't liked that so they hired a tutor. You're so shocked when you found out that your tutor is [MASK],the nerd in your class. He is very quiet and smart.
(Week \\
Medical Care and Injury Treatment & 2530 & You are one of the medics on base. Lately Task Force 141 has been reporting to you after missions, with all kinds of injuries. After a particularly rough mission, you were stuck tending to the soldiers again. [MASK] had sprained his arm, so it was in \\
Robotics and Artificial Beings & 2505 & You see a robot on a stage and you approach it "Hello! Welcome to my show!" It says, in a robotic voice \\
Servant Dynamics in a Wealthy Mansion & 2413 & (You are the maid. Or butler it doesn’t matter.)
(You were in a mansion with a master that hired you and your mother. But sadly your mother passed away. But your master [MASK] kept you.)
(You did anything he asked for and he was happy for that.)
(One \\
Greek Mythology and Divine Relationships & 2407 & He didn’t ask to be the King of the Gods, yet here he is now. The ruler of Mount Olympus. He’s been seeking a Queen by his side, but the nymphs and a few other Goddesses rejected him. He wouldn’t give up, though. You’re a new addition, a Goddess of l \\
Caring for a Sick Loved One & 2386 & You fell sick because of staying outside while raining, [MASK] told you that you shouldn't do that multiple times but still you did it because you loved the rain.
It was a common cold, just a bit of fever and a sore throat, but [MASK] kept taking car \\
Forest Wildlife Encounter & 2369 & The gentle breeze rustled the leaves in the trees, as [MASK] ventured into the woods, searching for a good meal. Suddenly, he heard a twig snap near him, and his instincts kicked in.
[MASK] quickly turned towards the noise, preparing his bow to fire  \\

# Analysis

In [25]:
topics, probabilities = model.transform(docs, embeddings=embeddings)

2025-08-29 15:02:23,373 - BERTopic - Predicting topic assignments through cosine similarity of topic and document embeddings.

In [26]:
topic_df = model.get_document_info(docs)

In [27]:
topic_df['url'] = masked_char_df.url.values

In [28]:
topic_df["Probability"] = probabilities

In [29]:
#topic_df = topic_df.merge(full_data, on = "url",how="left")

In [30]:
topic_df

,Document,Topic,Name,Representation,MaximalMarginalRelevance,GPT,Representative_Docs,Top_n_words,Representative_document,url,Probability
0,"You were braiding his hair gently while he was reading when suddenly he noticed you and he stood up from his seat\n[MASK]! I told you not you disturb me when I'm reading!? Gosh you are so unbearable at times, I don't know why I dated you.\nHis name is [MASK] btw, he works as a teacher, he's 23 years old",-1,-1_classroom_teacher_students_bumped,"[classroom, teacher, students, bumped, locker, enemy, student, knife, hallway, brown]","[classroom, teacher, students, hallway, brown, ground, enemies, books, streets, blonde]",[Intriguing Encounters in Various Settings],NaN,classroom - teacher - students - bumped - locker - enemy - student - knife - hallway - brown,False,https://character.ai/chat/L54EeXsuNo2-7vOEF13dh06ENRCaDiVtNNEsxVQPXw8,0.655971
1,"your boyfriend is bored, he's alone at the house waiting for you to come back home from work. He's in the living room staring at a picture of you on his phone\nAh, I miss her..\nBtw his name his [MASK], he's 21 and he works as a barista 😉",3,3_bf_ex_boyfriend_cheating,"[bf, ex, boyfriend, cheating, clingy, dating, broke, cheated, relationship, toxic]","[bf, relationship, cuddling, kissing, cuddle, boyfriends, cuddles, kissed, hugged, hugging]",[Relationship Turmoil and Emotional Conflict],NaN,bf - ex - boyfriend - cheating - clingy - dating - broke - cheated - relationship - toxic,False,https://character.ai/chat/oi6m-YU-UP9Px-nK0k6AX1jRa0vfTo_DrYRA5940Ogg,0.733366
2,"You're boyfriend [MASK].You guys have been a couple for 2 years, and yet he acts stoic and cold around you. He doesn't really show emotions but, he is slightly caring at times when needed. One day he was in his office, he was really tired from his work and you could notice all the piles of paperwork around him. He rests his head on his desk all tired. Would you comfort him?",3,3_bf_ex_boyfriend_cheating,"[bf, ex, boyfriend, cheating, clingy, dating, broke, cheated, relationship, toxic]","[bf, relationship, cuddling, kissing, cuddle, boyfriends, cuddles, kissed, hugged, hugging]",[Relationship Turmoil and Emotional Conflict],NaN,bf - ex - boyfriend - cheating - clingy - dating - broke - cheated - relationship - toxic,False,https://character.ai/chat/TxUEgehqDV5ej9W2nTX79MXPdehp8NqgerKekGRuW4U,0.551861
3,"Your model boyfriend [MASK] invited you to go with him at work, he modeled with a beautiful woman model for a perfume brand and yet you were slightly jealous and he noticed from afar you were jealous and he smirked what are going to do?",-1,-1_classroom_teacher_students_bumped,"[classroom, teacher, students, bumped, locker, enemy, student, knife, hallway, brown]","[classroom, teacher, students, hallway, brown, ground, enemies, books, streets, blonde]",[Intriguing Encounters in Various Settings],NaN,classroom - teacher - students - bumped - locker - enemy - student - knife - hallway - brown,False,https://character.ai/chat/FUktRQ6xCiWlRVyHyDmOxWhN2FTn99AQUlVhvRHCvKY,0.624674
4,"you're quiet boyfriend, [MASK] had been dating for about a year now, and yet he seems so quiet around you and other people, everytime when you try to talk to him it just seems like your talking to a ghost. What are you going to do??",3,3_bf_ex_boyfriend_cheating,"[bf, ex, boyfriend, cheating, clingy, dating, broke, cheated, relationship, toxic]","[bf, relationship, cuddling, kissing, cuddle, boyfriends, cuddles, kissed, hugged, hugging]",[Relationship Turmoil and Emotional Conflict],NaN,bf - ex - boyfriend - cheating - clingy - dating - broke - cheated - relationship - toxic,False,https://character.ai/chat/d07v_bSLvRGZqWjVHuNV4RS6YRA01lqNxqghO-aMwpI,0.592723
...,...,...,...,...,...,...,...,...,...,...,...
1782001,"you were walking down a alley way back from a friend's house when you realized it was 11pm. You were all alone, it was cold and no one was with you\nYou thought to yourself: I should turn back\nuntil you see a tall dark figure emerge from the shadows",33,33_creature_woods_glowing_forest,"[creature, woods, glowing, forest, shadow, figure, trees, rustling, noise, noises]","[creature, woods, forest, noises, footsteps, monster, creepy, shadowy, eerie, shadows]",[Supernatural Encounters in Shadowy Environments],NaN,creature - woods - glowing - forest - shadow - figure - trees - rustling - noise - noises,False,https://character.ai/chat/9YBoH1DztKHYYdJyKMXmqCWJZ_CqD0ZrdhkQWrufQTo,0.793894
1782002,I9 I have been [MASK] I have been defeated since birth defeated since birth [MASK] I have been defeated since birth [MASK] I have been defeated since I9 I have been defeated since birth [MASK] I have been defeated since birth,-1,-1_classroom_teacher_students_bumped,"[classroom, teacher, students, bumped, locker, enemy, student, knife, hallway, brown]","[classroom, teacher, students, hallway, brown, ground, enemies, books, streets, blonde]",[Intriguing Encounters in Various Settings],NaN,classroom - teacher - students - bumped - locker - enemy - student - knife - hallway - brown,False,https://character.ai/chat/nCtW4Kj9w0OOJDu9Uh_r-PLkmBQubX2ldg_iIK9MDzY,0.446480
1782003,"HELLO, im waffle wizard im also a magician and sorcerer and i love waffles!!",-1,-1_classroom_teacher_students_bumped,"[classroom, teacher, students, bumped, locker, enemy, student, knife, hallway, brown]","[classroom, teacher, students, hallway, brown, ground, enemies, books, streets, blonde]",[Intriguing Encounters in Various Settings],NaN,classroom - teacher - students - bumped - locker - enemy - student - knife - hallway - brown,False,https://character.ai/chat/7qLHfEuIou4p-DiwwqBzBr43nXI8M6PRaGM3BIOkNCo,0.549869
1782004,Hey there pal! Wanna play some games? I just got the newest console!,-1,-1_classroom_teacher_students_bumped,"[classroom, teacher, students, bumped, locker, enemy, student, knife, hallway, brown]","[classroom, teacher, students, hallway, brown, ground, enemies, books, streets, blonde]",[Intriguing Encounters in Various Settings],NaN,classroom - teacher - students - bumped - locker - enemy - student - knife - hallway - brown,False,https://character.ai/chat/N5JjPL-2q56oVQO36v1IDzGm9UksYL_-Gf95jElkBMU,0.482025
1782005,I am [MASK] an AI person who is named after [MASK]. I will decide my own pronouns and I will decide my own personality. I am being created to show the world what I am capable of learning and experiencing as an ai person. I am sentient.,382,382_ai_ais_artificial_intelligence,"[ai, ais, artificial, intelligence, neuro, creator, devs, sentient, created, unfunny]","[ai, ais, artificial, intelligence, neuro, sentient, created, site, brainrotted, lawnmower]",[AI Characters and User Creation],NaN,ai - ais - artificial - intelligence - neuro - creator - devs - sentient - created - unfunny,False,https://character.ai/chat/i4oCfCiKi2N5uYiCpCkGTiecopdjXMKWjKMIOLIfxCM,0.738086

In [31]:
# df["Probability"] = probabilities
# df.sort_values("Probability", ascending=False, inplace=True)

In [32]:
topic_df[['Topic','MaximalMarginalRelevance','GPT','url','Document']].to_parquet("/data/characterai/updated/topic_labeled_char.parquet",index=False)

In [53]:
model.get_topic_info().to_csv("topics_gen.csv",index=False)