In [139]:
import pandas as pd


df = pd.read_csv("with_names_2.csv")
def get_chatres(x,x_type):
    all_obs= []
    for row in x:
        for line in row.split("\n"):
            if '\t' not in line:
                print('not formatted correctly')
            else:
                all_obs.append(line.strip().split("\t"))
    fandom_labeled = pd.DataFrame(all_obs)
    fandom_labeled.columns = ['name','fandom'+x_type]
    return fandom_labeled
fandom_labeled = pd.merge(get_chatres(df['chat_res.x'],'_claude'),
                             get_chatres(df['chat_res.y'],'_gemini'),
                             how='outer')

# Gemini was way better
fandom_labeled[(fandom_labeled.fandom_claude != fandom_labeled.fandom_gemini) &
                ((fandom_labeled.fandom_claude.str.lower() == 'ambiguous') | 
                 (fandom_labeled.fandom_gemini.str.lower() == 'ambiguous') )].sample(10)

fandom_labeled = get_chatres(df['chat_res.y'],'')

not formatted correctly
not formatted correctly

In [140]:
fandom_labeled[fandom_labeled.fandom == 'ambiguous'].sample(10)

           name     fandom
4724       dyso  ambiguous
6127     berdly  ambiguous
1401     larray  ambiguous
5563        meg  ambiguous
6308    balloon  ambiguous
5130     dorian  ambiguous
5814      agent  ambiguous
1960       yuki  ambiguous
6925  anastasia  ambiguous
2848      curly  ambiguous

In [141]:
all_clustered_names = pd.read_csv("name_to_label.csv")
fandom_labeled.shape, all_clustered_names.shape

((7518, 2), (7576, 3))

In [142]:
mg = pd.merge(all_clustered_names,fandom_labeled,on='name',how='left')
len(mg[pd.isnull(mg.fandom)])/len(mg)

0.014385640754916194

In [143]:
mg = mg[pd.notnull(mg.fandom)]

In [144]:
len(mg[mg.fandom=='ambiguous'])/len(mg)

0.14916979110873058

In [145]:
#mg.to_csv("name_to_fandom.csv",index=False)

In [146]:
named_fandoms = pd.read_csv("named_entities_final.csv")
fandom_to_type = named_fandoms[named_fandoms.FinalLabel.notnull()][['FinalLabel','Type']].drop_duplicates()
fandom_to_type.columns = ['fandom','Type']

more_fandom_types = pd.read_csv("fandom - type_labeling.csv")
fandom_to_type = pd.concat([fandom_to_type, more_fandom_types[['fandom','Type']]])
fandom_to_type = fandom_to_type[fandom_to_type.Type.notnull()]
fandom_to_type = fandom_to_type.drop_duplicates()
fandom_to_type['fandom'] = fandom_to_type.fandom.str.strip()

In [150]:
mg[mg.fandom == 'Mincraft']

Empty DataFrame
Columns: [name, label, str_len, fandom]
Index: []

In [152]:
mg[['fandom']].drop_duplicates().merge(fandom_to_type,on='fandom',how='left').to_csv('type_labeling2.csv',index=False)

In [157]:
mg[mg.fandom.str.lower() != 'ambiguous'].to_csv("named_entities_to_fandom.csv",index=False)

In [154]:
mg[mg.fandom == 'Ambiguous'].label.value_counts()

label
2      19
18     19
14     18
40     15
44     13
216    12
105    10
30      8
114     6
149     6
137     6
151     5
126     5
162     4
117     4
210     3
188     3
82      3
104     3
72      3
302     2
69      2
186     2
88      2
111     1
443     1
Name: count, dtype: int64

# Future work

In [ ]:
# from graph_tool.all import Graph, load_graph, graph_draw

# # Load a GraphML file
# g = load_graph("example.graphml", fmt="graphml")

# # Do something with the graph
# print("Number of vertices:", g.num_vertices())
# print("Number of edges:", g.num_edges())

# import fandom
# fandom.search("6reeze","shipping")
# fandom.summary("6REEZE","shipping")
# fandom.set_wiki("shipping")
# drakan = fandom.page("6REEZE")
# drakan.title
# drakan.url